=== Kaushalgurung/Downtown-Records/catalog_19031057.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT MusicStore (info,PlayLists)>
<!ATTLIST MusicStore
  xmlns CDATA #FIXED ''
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>

<!ELEMENT info (MusicStore_Name,Address,Telephone_No,Website_Address,
                Logo)>
<!ATTLIST info
  xmlns CDATA #FIXED ''>

<!ELEMENT PlayLists (Songs)>
<!ATTLIST PlayLists
  xmlns CDATA #FIXED ''>

<!ELEMENT MusicStore_Name (#PCDATA)>
<!ATTLIST MusicStore_Name
  xmlns CDATA #FIXED ''>

<!ELEMENT Address (#PCDATA)>
<!ATTLIST Address
  xmlns CDATA #FIXED ''>

<!ELEMENT Telephone_No (#PCDATA)>
<!ATTLIST Telephone_No
  xmlns CDATA #FIXED ''>

<!ELEMENT Website_Address (#PCDATA)>
<!ATTLIST Website_Address
  xmlns CDATA #FIXED ''>

<!ELEMENT Logo EMPTY>
<!ATTLIST Logo
  xmlns CDATA #FIXED ''
  image NMTOKEN #REQUIRED>

<!ELEMENT Songs (Music)+>
<!ATTLIST Songs
  xmlns CDATA #FIXED ''>

<!ELEMENT Music (Name,Image,Album-Type,Artist,Genre,Realesed-Date,
                 Duration,Track)>
<!ATTLIST Music
  xmlns CDATA #FIXED ''
  ID_no NMTOKEN #REQUIRED
  Label CDATA #REQUIRED
  Language CDATA #REQUIRED>

<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name
  xmlns CDATA #FIXED ''>

<!ELEMENT Image EMPTY>
<!ATTLIST Image
  xmlns CDATA #FIXED ''
  id NMTOKEN #REQUIRED>

<!ELEMENT Album-Type (#PCDATA)>
<!ATTLIST Album-Type
  xmlns CDATA #FIXED ''>

<!ELEMENT Artist (desc)+>
<!ATTLIST Artist
  xmlns CDATA #FIXED ''>

<!ELEMENT Genre (#PCDATA)>
<!ATTLIST Genre
  xmlns CDATA #FIXED ''>

<!ELEMENT Realesed-Date (#PCDATA)>
<!ATTLIST Realesed-Date
  xmlns CDATA #FIXED ''>

<!ELEMENT Duration (#PCDATA)>
<!ATTLIST Duration
  xmlns CDATA #FIXED ''>

<!ELEMENT Track (desc)+>
<!ATTLIST Track
  xmlns CDATA #FIXED ''>

<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc
  xmlns CDATA #FIXED ''>

=== Kaushalgurung/Downtown-Records/catalog_19031057.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
Author: Kaushal Gurung
Date: 2nd May, 2021 
Note: Keep Zoom-90% in the Google Chrome while opening xml file.
-->
<!DOCTYPE MusicStore SYSTEM "catalog_19031057.dtd">
<?xml-stylesheet href="catalog_19031057.css" type="text/css"?> 
<MusicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031057.xsd">
    <info>
        <MusicStore_Name>Downtown Records</MusicStore_Name>
        <Address>Address: 3-27-3 Toyo, Koto-ku,Tokyo</Address>
        <Telephone_No>Contact: 03 3645 0155</Telephone_No>
        <Website_Address>www.downtownrecords.jp</Website_Address>
        <Logo image="img"></Logo>
    </info>
    <PlayLists>
        <Songs>
            <Music ID_no="ID_1" Language="English,Korean" Label="YG">
                <Name>  The Album </Name> 
                <Image id="image_1"></Image>
                <Album-Type>Studio</Album-Type>
                <Artist>
                    <desc>Jisoo- Vocals (all tracks),lyricist (track5)</desc>
                    <desc>Jennie – vocals (all tracks), lyricist, composer (track 5)</desc>
                    <desc>Rosé – vocals (all tracks)</desc>
                    <desc>Lisa – vocals (all tracks)</desc>
                    <desc>Selena Gomez – vocals, composer (track 2)</desc>
                    <desc>Cardi B – vocals, lyricist (track 4)</desc>
                </Artist>
                <Genre> Pop, RnB, EDM, Hiphop, Trap </Genre>
                <Realesed-Date>October 2, 2020</Realesed-Date>
                <Duration>24:26 min </Duration>
                <Track>
                    <desc>How You Like That</desc>
                    <desc>Ice Cream</desc>
                    <desc>Bet You Wanna</desc>
                    <desc>Pretty Savage</desc>
                    <desc>Lovesick Girls</desc>
                    <desc>Crazy Over You</desc>
                    <desc>Love to Hate Me</desc>
                    <desc>You Never Know</desc>
                </Track>
            </Music>
            <Music ID_no="ID_2" Language="English" Label="DGC">
                <Name>Nevermind</Name>
                <Image id="image_2" />
                <Album-Type>Studio</Album-Type>
                <Artist>
                    <desc>Kurt Cobain</desc>
                    <desc>Krist Novoselic</desc>
                    <desc>Dave Grohl</desc>
                </Artist>
                <Genre> pop</Genre>
                <Realesed-Date>	September 24, 1991</Realesed-Date>
                <Duration>49:07 mins</Duration>
                <Track>
                    <desc>Smells Like Teen Spirit </desc>
                    <desc>In Bloom</desc>
                    <desc>Come as You Are</desc>
                    <desc>Breed</desc>
                    <desc>Lithium</desc>
                    <desc>Polly</desc>
                    <desc>Territorial Pissings</desc>
                    <desc>Drain You</desc>
                    <desc>Lounge Act</desc>
                    <desc>Stay Away</desc>
                    <desc>On a Plain</desc>
                    <desc>Something in the Way</desc>
                    <desc>Endless, Nameless</desc>
                </Track>
            </Music>
            <Music ID_no="ID_3" Language="Nepali" Label="Albatross Nepal">
                <Name>  Atti Bhayo (अत्ति भयो) </Name> 
                <Image id="image_3"></Image>
                <Album-Type>Studio</Album-Type>
                <Artist>
                    <desc>Shirish Dali</desc>
                    <desc>Sunny Manandhar (Suncha Vox)</desc>
                    <desc>Avaya Siddhi Bajracharya</desc>
                    <desc>Kismat D Shrestha</desc>
                </Artist>
                <Genre> Pop </Genre>
                <Realesed-Date>December 31, 2009</Realesed-Date>
                <Duration>34:39 min </Duration>
                <Track>
                    <desc>Maa</desc>
                    <desc>Shristi Ra Dristi</desc>
                    <desc>Janta Ma Appeal</desc>
                    <desc>Jhari Ko Raat</desc>
                    <desc>Chaina</desc>
                    <desc>Nischal</desc>
                    <desc>Abhiman</desc>
                    <desc>Kahile Kahi</desc>
                </Track>
            </Music>
            <Music ID_no="ID_4" Language="Japanese,English" Label="Sony Music Records">
                <Name>Toxic</Name>
                <Image id="image_4" />
                <Album-Type>Studio</Album-Type>
                <Artist>
                    <desc>Ruki- Vocalist</desc>
                    <desc>Uruha- Lead Guitarist</desc>
                    <desc>Kai- Acoustic Drummer</desc>
                    <desc>Reita- Bass Guitar</desc>
                    <desc>Aoi- Guitar</desc>
                    <desc>Yune- Acoustic Drummer</desc>
                </Artist>
                <Genre> Alternative metal, Industrial metal, Metalcore, Progressive rock</Genre>
                <Realesed-Date>	October 5, 2011</Realesed-Date>
                <Duration>50:28 mins</Duration>
                <Track>
                    <desc>Infuse Into </desc>
                    <desc>Venemous Spider's Web</desc>
                    <desc>Sludgy Cult</desc>
                    <desc>Red</desc>
                    <desc>Suicide Circus</desc>
                    <desc>Shiver</desc>
                    <desc>My Devil On The Bed</desc>
                    <desc>Untitled</desc>
                    <desc>Pledge</desc>
                    <desc>Ruthless Deed</desc>
                    <desc>Psychopath</desc>
                    <desc>Vortex</desc>
                    <desc>Tomorrow Never Dies</desc>
                    <desc>Omega</desc>
                </Track>
            </Music>
        <Music ID_no="ID_5" Language="English" Label="Parlophone">
            <Name>  Revolver </Name> 
            <Image id="image_5"></Image>
            <Album-Type>Studio</Album-Type>
            <Artist>
                <desc>John Lennon</desc>
                <desc>Paul McCartney</desc>
                <desc>George Harrison</desc>
                <desc>Ringo Starr</desc>

            </Artist>
            <Genre> Pop, RnB, EDM, Hiphop, Trap </Genre>
            <Realesed-Date>October 2, 2020</Realesed-Date>
            <Duration>24:26 min </Duration>
            <Track>
                <desc>Taxman</desc>
                <desc>Eleanor Rigby</desc>
                <desc>I'm Only Sleeping</desc>
                <desc>Love You To</desc>
                <desc>Here, There and Everywhere</desc>
                <desc>Yellow Submarine</desc>
                <desc>She Said She Said</desc>
            </Track>
        </Music>
        <Music ID_no="ID_6" Language="English" Label="Rolling Stones">
            <Name>Some Girls</Name>
            <Image id="image_6" />
            <Album-Type>Studio</Album-Type>
            <Artist>
                <desc> Mick Jagger</desc>
                <desc>Keith Richards</desc>
                <desc>Brian Jones </desc>
                <desc>Bill Wyman</desc>
                <desc>Charlie Watts</desc>
            </Artist>
            <Genre> Rockpunk rock, Disco, Country</Genre>
            <Realesed-Date> June 9, 1978</Realesed-Date>
            <Duration>40:45 mins</Duration>
            <Track>
                <desc>Miss You </desc>
                <desc>When the Whip Comes Down</desc>
                <desc>Just My Imagination (Running Away with Me)</desc>
                <desc>Some Girls</desc>
                <desc>Lies</desc>
                <desc>Far Away Eyes</desc>
                <desc>Respectable</desc>
                <desc>Before They Make Me Run</desc>
                <desc>Beast of Burden</desc>
                <desc>Shattered</desc>
            </Track>
        </Music>
        <Music ID_no="ID_7" Language="English" Label="Harvest">
            <Name>  The Dark Side of the Moon </Name> 
            <Image id="image_7"></Image>
            <Album-Type>Studio</Album-Type>
            <Artist>
                <desc>Syd Barrett – lead and rhythm guitars, vocals</desc>
                <desc>Nick Mason – drums, percussion, vocals</desc>
                <desc>Roger Waters – bass, vocals, rhythm guitar </desc>
                <desc>Richard Wright – keyboards, piano, organ, vocals</desc>
                <desc>David Gilmour – lead and rhythm guitars, vocals, bass, keyboards</desc>
                <desc>Bob Klose – lead guitar </desc>
            </Artist>
            <Genre> Progressive rock </Genre>
            <Realesed-Date>1 March 1973</Realesed-Date>
            <Duration>43:09 min </Duration>
            <Track>
                <desc>Speak to Me</desc>
                <desc>Breathe</desc>
                <desc>On the Run"</desc>
                <desc>Time</desc>
                <desc>The Great Gig in the Sky</desc>
                <desc>Money</desc>
                <desc>Any Colour You Like</desc>
                <desc>Brain Damage</desc>
                <desc>Eclipse</desc>
            </Track>
        </Music>
        <Music ID_no="ID_8" Language="English" Label="EMI">
            <Name>Queen II</Name>
            <Image id="image_8" />
            <Album-Type>Studio</Album-Type>
            <Artist>
                <desc>Kurt Cobain</desc>
                <desc>Krist Novoselic</desc>
                <desc>Dave Grohl</desc>
            </Artist>
            <Genre> Progressive rock</Genre>
            <Realesed-Date>	September 24, 1991</Realesed-Date>
            <Duration>40:42 mins</Duration>
            <Track>
                <desc>Procession </desc>
                <desc>Father to Son</desc>
                <desc>White Queen (As It Began)</desc>
